import { describe, it, expect } from "bun:test";
import { FileExtensions } from "../src/types";
import formatTranslatedContent from "../src/helpers/formatTranslatedContent";

describe("formatTranslatedContent", () => {
  const mockTranslations = {
    namespace1: {
      greeting: "Hello",
      farewell: "Goodbye",
    },
    namespace2: {
      welcome: "Welcome",
      goodbye: "Goodbye",
    },
  };

  it("should format content as JSON (primary language)", () => {
    const result = formatTranslatedContent({
      fileExtension: ".json" as FileExtensions,
      translatedContent: mockTranslations,
      targetLanguage: "en",
      isPrimary: true,
    });

    // Expect valid JSON
    let parsed;
    expect(() => {
      parsed = JSON.parse(result);
    }).not.toThrow();

    // Check the special `_generatedByTranslateSheet` message for primary
    expect(parsed._generatedByTranslateSheet).toContain(
      "This file was generated by TranslateSheet. Do NOT edit this file directly. To change primary language strings"
    );

    // Check that actual translation keys got included
    expect(parsed.namespace1.greeting).toBe("Hello");
    expect(parsed.namespace1.farewell).toBe("Goodbye");
    expect(parsed.namespace2.welcome).toBe("Welcome");
    expect(parsed.namespace2.goodbye).toBe("Goodbye");
  });

  it("should format content as JSON (non-primary language)", () => {
    const result = formatTranslatedContent({
      fileExtension: ".json" as FileExtensions,
      translatedContent: mockTranslations,
      targetLanguage: "es",
      isPrimary: false,
    });

    let parsed;
    expect(() => {
      parsed = JSON.parse(result);
    }).not.toThrow();

    // Check the special `_generatedByTranslateSheet` message for non-primary
    expect(parsed._generatedByTranslateSheet).toContain(
      "This file was generated by TranslateSheet. Do NOT edit this file directly. Make changes in the TranslateSheet dashboard."
    );

    expect(parsed.namespace1.greeting).toBe("Hello");
    expect(parsed.namespace1.farewell).toBe("Goodbye");
    expect(parsed.namespace2.welcome).toBe("Welcome");
    expect(parsed.namespace2.goodbye).toBe("Goodbye");
  });

  it("should format content as TypeScript (primary language)", () => {
    const result = formatTranslatedContent({
      fileExtension: ".ts" as FileExtensions,
      translatedContent: mockTranslations,
      targetLanguage: "en",
      isPrimary: true,
    });

    // We expect a comment plus the TS content from formatAsTypeScript
    expect(result).toContain("// This file was generated by TranslateSheet.");
    expect(result).toContain(
      "To change primary language strings, update your TranslateSheet object declarations."
    );
    // Rough check for the actual TS export structure
    expect(result).toContain("export default");
    expect(result).toContain("greeting");
  });

  it("should format content as TypeScript (non-primary language)", () => {
    const result = formatTranslatedContent({
      fileExtension: ".ts" as FileExtensions,
      translatedContent: mockTranslations,
      targetLanguage: "ja",
      isPrimary: false,
    });

    expect(result).toContain("// This file was generated by TranslateSheet.");
    expect(result).toContain("Make changes in the TranslateSheet dashboard.");
    expect(result).toContain("export default");
    expect(result).toContain("greeting");
  });

  it("should format content as JavaScript", () => {
    const result = formatTranslatedContent({
      fileExtension: ".js" as FileExtensions,
      translatedContent: mockTranslations,
      targetLanguage: "de",
      isPrimary: true, // or false—both produce a similar pattern except the comment changes slightly
    });

    expect(result).toContain("// This file was generated by TranslateSheet.");
    expect(result).toContain("export default");
    expect(result).toContain("greeting");
  });

  it("should throw for an unsupported file extension", () => {
    expect(() =>
      formatTranslatedContent({
        fileExtension: ".txt" as FileExtensions,
        translatedContent: mockTranslations,
        targetLanguage: "en",
      })
    ).toThrow("Unsupported file extension: .txt");
  });
});
