// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

import { Translations } from "./translations.types";
  
  const es: Translations = {
  GiveConsentText: {
    body: "Si necesita cambiar el contenido,\nsus detalles del evento se guardarán.",
    giveConsent: "Al presionar “Continuar” acepta nuestra <privacyLink>Política de privacidad</privacyLink> y <termsLink>Términos</termsLink> y consiente en recibir mensajes de texto de nuestra parte. Se aplican tarifas de mensajes y datos. Envíe STOP en cualquier momento para cancelar.",
  },
  TestInput: {
    buttonLabel: "PRESIONAR",
    buttonVal: "El valor del booleano es: {{value}}",
    inputVal: "El valor de la prueba es: {{value}}",
  },
  common: {
    hello: "Hola",
    title: "Esta pantalla no existe.",
    link: "¡Ir a la pantalla de inicio!",
    hello2: "esto es una prueba hermano",
  },
  HomeScreen: {
    headerTitle: "¡Bienvenido! {{name}}",
    step1: {
      title: "Paso 1: Pruébalo",
      editText: "Editar",
      pressChanges: "para ver cambios. Presione",
      devTools: "para abrir las herramientas de desarrollo.",
    },
    step2: {
      title: "Paso 2: Explora",
      description: "Toque la pestaña Explorar para obtener más información sobre lo que incluye esta aplicación de inicio.",
    },
    step3: {
      title: "Paso 3: Empieza de nuevo",
      runCommand: "Cuando estés listo, ejecuta",
      freshApp: "para obtener una nueva ",
      appText: "aplicación",
      to: "a",
      moveDir: "directorio. Esto moverá el actual",
      appExample: "ejemplo-de-aplicacion",
    },
    languageSelect: "Seleccionar Idioma",
  },
  TabTwoScreen: {
    exploreTitle: "Explorar",
    introduction: "Esta aplicación incluye código de ejemplo para ayudarte a comenzar.",
    routingTitle: "Enrutamiento basado en archivos",
    routingScreens: "Esta aplicación tiene dos pantallas:",
    routingLayout: "El archivo de diseño en",
    routingSetsUp: "configura el navegador de pestañas.",
    routingLearnMore: "Más información",
    platformTitle: "Compatibilidad con Android, iOS y web",
    platformDescription: "Puedes abrir este proyecto en Android, iOS y la web. Para abrir la versión web, presiona",
    imagesTitle: "Imágenes",
    imagesDescription: "Para imágenes estáticas, puedes usar el",
    imagesAnd: "y",
    imagesSuffixes: "sufijos para proporcionar archivos para diferentes densidades de pantalla",
    fontsTitle: "Fuentes personalizadas",
    fontsDescription: "Abrir",
    fontsLoad: "para ver cómo cargar",
    fontsExample: "fuentes personalizadas como esta.",
    themeTitle: "Componentes de modo claro y oscuro",
    themeDescription: "Esta plantilla tiene soporte para modo claro y oscuro. El",
    themeInspect: "hook te permite inspeccionar cuál es el esquema de color actual del usuario, por lo que puedes ajustar los colores de la interfaz de usuario en consecuencia.",
    animationsTitle: "Animaciones",
    animationsDescription: "Esta plantilla incluye un ejemplo de un componente animado. El",
    animationsUses: "componente utiliza la poderosa",
    animationsLib: "biblioteca para crear una animación de saludo con la mano.",
    animationsParallax: "componente proporciona un efecto de paralaje para la imagen de encabezado.",
    translateTitle: "Traducción y localización",
    translateDescription: "Esta aplicación utiliza TranslateSheet para gestionar traducciones.",
    translateInline: "Las traducciones se definen en línea con componentes utilizando",
    translateCli: "Ejecutar",
    translateGenerate: "para generar archivos de traducción.",
    translateSwitch: "La aplicación admite un cambio dinámico de idioma sin necesidad de recargar la aplicación.",
    translateLearnMore: "Más información",
  },
  TabLayout: {
    home: "Inicio",
    explore: "Explorar",
    yoyo: "Yoyo",
    nope: "Nope",
  },
};
export default es;