// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

import { Translations } from "./translations.types";
  
  const es: Translations = {
  GiveConsentText: {
    body: "Si necesita cambiar el contenido, \nse guardarán los detalles de su evento.",
    giveConsent: "Al presionar “Continuar” aceptas nuestra <privacyLink>Política de privacidad</privacyLink> y <termsLink>Términos</termsLink> y das tu consentimiento para recibir mensajes de texto de nuestra parte. Se aplican tarifas de mensajes y datos. En cualquier momento, envía STOP para cancelar.",
  },
  TestInput: {
    buttonLabel: "PRESIONA ME",
    buttonVal: "El valor del booleano es: {{value}}",
    inputVal: "El valor de la entrada de prueba es: {{value}}",
  },
  common: {
    hello: "Hola",
    title: "Esta pantalla no existe.",
    link: "¡Ve a la pantalla de inicio!",
    hello2: "esto es una prueba, hermano",
  },
  HomeScreen: {
    headerTitle: "¡Bienvenido! {{name}}",
    step1: {
      title: "Paso 1: Pruébalo",
      editText: "Editar",
      pressChanges: "para ver los cambios. Presiona",
      devTools: "para abrir las herramientas de desarrollo.",
    },
    step2: {
      title: "Paso 2: Explora",
      description: "Toca la pestaña Explorar para obtener más información sobre lo que incluye esta aplicación inicial.",
    },
    step3: {
      title: "Paso 3: Comienza de nuevo",
      runCommand: "Cuando estés listo, ejecuta",
      freshApp: "para obtener una nueva ",
      appText: "aplicación",
      to: "a",
      moveDir: "directorio. Esto moverá el actual",
      appExample: "ejemplo-de-aplicacion",
    },
    languageSelect: "Seleccionar Idioma",
  },
  TabTwoScreen: {
    exploreTitle: "Explorar",
    introduction: "Esta aplicación incluye código de ejemplo para ayudarte a empezar.",
    routingTitle: "Enrutamiento basado en archivos",
    routingScreens: "Esta aplicación tiene dos pantallas:",
    routingLayout: "El archivo de diseño en",
    routingSetsUp: "configura el navegador de pestañas.",
    routingLearnMore: "Saber más",
    platformTitle: "Soporte para Android, iOS y web",
    platformDescription: "Puedes abrir este proyecto en Android, iOS y la web. Para abrir la versión web, presiona",
    imagesTitle: "Imágenes",
    imagesDescription: "Para imágenes estáticas, puedes usar el",
    imagesAnd: "y",
    imagesSuffixes: "sufijos para proporcionar archivos para diferentes densidades de pantalla",
    fontsTitle: "Fuentes personalizadas",
    fontsDescription: "Abre",
    fontsLoad: "para ver cómo cargar",
    fontsExample: "fuentes personalizadas como esta.",
    themeTitle: "Componentes de modo claro y oscuro",
    themeDescription: "Esta plantilla tiene soporte para modo claro y oscuro. El",
    themeInspect: "gancho te permite inspeccionar cuál es el esquema de color actual del usuario, y así puedes ajustar los colores de la interfaz de usuario en consecuencia.",
    animationsTitle: "Animaciones",
    animationsDescription: "Esta plantilla incluye un ejemplo de un componente animado. El",
    animationsUses: "componente utiliza la potente",
    animationsLib: "biblioteca para crear una animación de mano saludando.",
    animationsParallax: "componente proporciona un efecto de paralaje para la imagen de encabezado.",
    translateTitle: "Traducción y localización",
    translateDescription: "Esta aplicación utiliza TranslateSheet para gestionar las traducciones.",
    translateInline: "Las traducciones se definen en línea con componentes utilizando",
    translateCli: "Ejecutar",
    translateGenerate: "para generar archivos de traducción.",
    translateSwitch: "La aplicación admite cambios de idioma dinámicos sin necesidad de recargar la aplicación.",
    translateLearnMore: "Saber más",
  },
  TabLayout: {
    home: "Inicio",
    explore: "Explorar",
    yoyo: "Yoyo",
    nope: "Nope",
  },
};
export default es;