// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

import { Translations } from "./translations.types";
  
  const ja: Translations = {
  GiveConsentText: {
    body: "コンテンツを変更する必要がある場合、\nイベントの詳細は保存されます。",
    giveConsent: "「続行」を押すと、<privacyLink>プライバシーポリシー</privacyLink>と<termsLink>利用規約</termsLink>に同意し、私たちからテキストメッセージを受け取ることに同意します。メッセージとデータ料金がかかります。キャンセルするにはいつでもSTOPと入力してください。",
  },
  TestInput: {
    buttonLabel: "押して",
    buttonVal: "ブール値は次のとおりです：{{value}}",
    inputVal: "testInputの値は次のとおりです：{{value}}",
  },
  common: {
    hello: "こんにちは",
    title: "この画面は存在しません。",
    link: "ホーム画面に移動！",
    hello2: "これはテストです",
  },
  HomeScreen: {
    headerTitle: "ようこそ！{{name}}",
    step1: {
      title: "ステップ1：試してみる",
      editText: "編集",
      pressChanges: "変更を確認するには。押す",
      devTools: "開発者ツールを開くには。",
    },
    step2: {
      title: "ステップ2：探索",
      description: "このスターターアプリに含まれる内容を学ぶには、探索タブをタップしてください。",
    },
    step3: {
      title: "ステップ3：新しいスタートを切る",
      runCommand: "準備ができたら、実行してください。",
      freshApp: "新しい",
      appText: "アプリ",
      to: "に",
      moveDir: "ディレクトリに移動します。これにより、現在の",
      appExample: "app-example",
    },
    languageSelect: "言語を選択",
  },
  TabTwoScreen: {
    exploreTitle: "探索",
    introduction: "このアプリには、始めるのに役立つサンプルコードが含まれています。",
    routingTitle: "ファイルベースのルーティング",
    routingScreens: "このアプリには2つの画面があります：",
    routingLayout: "レイアウトファイルは",
    routingSetsUp: "タブナビゲーターを設定します。",
    routingLearnMore: "詳細を確認",
    platformTitle: "Android、iOS、およびWebサポート",
    platformDescription: "このプロジェクトはAndroid、iOS、およびWebで開くことができます。Webバージョンを開くには、押してください。",
    imagesTitle: "画像",
    imagesDescription: "静的画像には、以下を使用できます",
    imagesAnd: "および",
    imagesSuffixes: "異なる画面密度用のファイルを提供するための接尾辞",
    fontsTitle: "カスタムフォント",
    fontsDescription: "開く",
    fontsLoad: "を見て、次のようにロードする方法を確認してください",
    fontsExample: "このようなカスタムフォントを使用する方法。",
    themeTitle: "ライトモードとダークモードのコンポーネント",
    themeDescription: "このテンプレートは、ライトモードとダークモードをサポートしています。",
    themeInspect: "フックを使用すると、ユーザーの現在のカラースキームを確認して、UIの色を適切に調整できます。",
    animationsTitle: "アニメーション",
    animationsDescription: "このテンプレートには、アニメーション化されたコンポーネントの例が含まれています。",
    animationsUses: "コンポーネントは、強力な",
    animationsLib: "ライブラリを使用して手を振るアニメーションを作成します。",
    animationsParallax: "コンポーネントは、ヘッダー画像のパララックス効果を提供します。",
    translateTitle: "翻訳とローカライゼーション",
    translateDescription: "このアプリは、TranslateSheetを使用して翻訳を管理しています。",
    translateInline: "コンポーネントとインラインで定義された翻訳を使用して",
    translateCli: "実行",
    translateGenerate: "翻訳ファイルを生成するには",
    translateSwitch: "アプリは、再読み込みせずに動的言語切り替えをサポートしています。",
    translateLearnMore: "詳細を確認",
  },
  TabLayout: {
    home: "ホーム",
    explore: "探索",
    yoyo: "ヨーヨー",
    nope: "いいえ",
  },
};
export default ja;