// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Run translate-sheet generate-types to regenerate this file.

export type Translations = {
  GiveConsentText: {
    body: string;
    giveConsent: string;
  };
  TestInput: {
    buttonLabel: string;
    buttonVal: string;
    inputVal: string;
  };
  common: {
    hello: string;
    title: string;
    link: string;
    hello2: string;
  };
  HomeScreen: {
    headerTitle: string;
    step1: {
      title: string;
      editText: string;
      pressChanges: string;
      devTools: string;
    };
    step2: {
      title: string;
      description: string;
    };
    step3: {
      title: string;
      runCommand: string;
      freshApp: string;
      appText: string;
      to: string;
      moveDir: string;
      appExample: string;
    };
    languageSelect: string;
  };
  TabTwoScreen: {
    exploreTitle: string;
    introduction: string;
    routingTitle: string;
    routingScreens: string;
    routingLayout: string;
    routingSetsUp: string;
    routingLearnMore: string;
    platformTitle: string;
    platformDescription: string;
    imagesTitle: string;
    imagesDescription: string;
    imagesAnd: string;
    imagesSuffixes: string;
    fontsTitle: string;
    fontsDescription: string;
    fontsLoad: string;
    fontsExample: string;
    themeTitle: string;
    themeDescription: string;
    themeInspect: string;
    animationsTitle: string;
    animationsDescription: string;
    animationsUses: string;
    animationsLib: string;
    animationsParallax: string;
    translateTitle: string;
    translateDescription: string;
    translateInline: string;
    translateCli: string;
    translateGenerate: string;
    translateSwitch: string;
    translateLearnMore: string;
  };
  TabLayout: {
    home: string;
    explore: string;
    yoyo: string;
    nope: string;
  };
};
