// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

import { Translations } from "./translations.types";
  
  const zh: Translations = {
  GiveConsentText: {
    body: "如果您需要更改内容，\n您的事件详情将被保存。",
    giveConsent: "按“继续”即表示您同意我们的<privacyLink>隐私政策</privacyLink>和<termsLink>条款</termsLink>并同意接收我们的短信。消息和数据费用适用。随时发送“STOP”取消。",
  },
  TestInput: {
    buttonLabel: "按我",
    buttonVal: "布尔值为：{{value}}的值",
    inputVal: "testInput的值为：{{value}}",
  },
  common: {
    hello: "您好",
    title: "此屏幕不存在。",
    link: "转到主屏幕！",
    hello2: "这是一个测试兄弟",
  },
  HomeScreen: {
    headerTitle: "欢迎！{{name}}",
    step1: {
      title: "第1步：试一试",
      editText: "编辑",
      pressChanges: "查看更改。按",
      devTools: "打开开发者工具。",
    },
    step2: {
      title: "第2步：探索",
      description: "点击“探索”选项卡以了解此初始应用程序中包含的内容。",
    },
    step3: {
      title: "第3步：重新开始",
      runCommand: "当您准备好时，运行",
      freshApp: "以获取一个新的",
      appText: "应用程序",
      to: "到",
      moveDir: "目录。这将移动当前",
      appExample: "应用示例",
    },
    languageSelect: "选择语言",
  },
  TabTwoScreen: {
    exploreTitle: "探索",
    introduction: "此应用程序包含示例代码，帮助您开始。",
    routingTitle: "基于文件的路由",
    routingScreens: "此应用程序有两个屏幕：",
    routingLayout: "位于的布局文件",
    routingSetsUp: "设置选项卡导航器。",
    routingLearnMore: "了解更多",
    platformTitle: "Android，iOS和Web支持",
    platformDescription: "您可以在Android，iOS和Web上打开此项目。要打开Web版本，请按",
    imagesTitle: "图片",
    imagesDescription: "对于静态图像，您可以使用",
    imagesAnd: "和",
    imagesSuffixes: "后缀为不同屏幕密度提供文件",
    fontsTitle: "自定义字体",
    fontsDescription: "打开",
    fontsLoad: "查看如何加载",
    fontsExample: "例如这样的自定义字体。",
    themeTitle: "明亮和暗黑模式组件",
    themeDescription: "此模板支持明亮和暗黑模式。",
    themeInspect: "挂钩让您检查用户当前的颜色方案，因此您可以相应地调整UI颜色。",
    animationsTitle: "动画",
    animationsDescription: "此模板包含一个动画组件的示例。",
    animationsUses: "组件使用强大的",
    animationsLib: "库创建了一个挥手动画。",
    animationsParallax: "组件为标题图像提供视差效果。",
    translateTitle: "翻译和本地化",
    translateDescription: "此应用程序使用TranslateSheet来管理翻译。",
    translateInline: "使用组件内联定义翻译",
    translateCli: "运行",
    translateGenerate: "生成翻译文件。",
    translateSwitch: "该应用支持动态语言切换，无需重新加载应用。",
    translateLearnMore: "了解更多",
  },
  TabLayout: {
    home: "主页",
    explore: "探索",
    yoyo: "哟哟",
    nope: "不",
  },
};
export default zh;