// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

import { Translations } from "./translations.types";
  
  const zh: Translations = {
  GiveConsentText: {
    body: "如果您需要更改内容，您的活动详细信息将被保存。",
    giveConsent: "按“继续”按钮即表示您同意我们的<privacyLink>隐私政策</privacyLink>和<termsLink>条款</termsLink>并同意接收我们的短信。 消息和数据费用适用。 随时发送“STOP”取消。",
  },
  TestInput: {
    buttonLabel: "按我",
    buttonVal: "布尔值是：{{value}}",
    inputVal: "testInput的值是：{{value}}",
  },
  common: {
    hello: "你好",
    title: "此屏幕不存在。",
    link: "转到主屏幕！",
    hello2: "这是一个测试，兄弟",
  },
  HomeScreen: {
    headerTitle: "欢迎！{{name}}",
    step1: {
      title: "步骤1：试一试",
      editText: "编辑",
      pressChanges: "查看更改。按",
      devTools: "打开开发人员工具。",
    },
    step2: {
      title: "步骤2：探索",
      description: "点击“探索”选项卡，了解此入门应用程序中包含的内容。",
    },
    step3: {
      title: "步骤3：重新开始",
      runCommand: "准备好后，运行",
      freshApp: "以获得一个全新的",
      appText: "应用程序",
      to: "至",
      moveDir: "目录。 这将移动当前",
      appExample: "app-example",
    },
    languageSelect: "选择语言",
  },
  TabTwoScreen: {
    exploreTitle: "探索",
    introduction: "此应用程序包含示例代码，帮助您入门。",
    routingTitle: "基于文件的路由",
    routingScreens: "此应用程序有两个屏幕：",
    routingLayout: "布局文件中的",
    routingSetsUp: "设置选项卡导航器。",
    routingLearnMore: "了解更多",
    platformTitle: "Android、iOS和Web支持",
    platformDescription: "您可以在Android、iOS和Web上打开此项目。 要打开Web版本，请按",
    imagesTitle: "图像",
    imagesDescription: "对于静态图像，您可以使用",
    imagesAnd: "和",
    imagesSuffixes: "后缀，为不同屏幕密度提供文件。",
    fontsTitle: "自定义字体",
    fontsDescription: "打开",
    fontsLoad: "查看如何加载",
    fontsExample: "诸如此类的自定义字体。",
    themeTitle: "明亮和暗模式组件",
    themeDescription: "此模板支持明亮和暗模式。 该",
    themeInspect: "钩子让您检查用户当前的颜色方案，从而可以相应地调整UI颜色。",
    animationsTitle: "动画",
    animationsDescription: "此模板包括一个动画组件的示例。 该",
    animationsUses: "组件使用强大的",
    animationsLib: "库创建了一个挥手动画。",
    animationsParallax: "组件为标题图像提供视差效果。",
    translateTitle: "翻译和本地化",
    translateDescription: "此应用程序使用TranslateSheet来管理翻译。",
    translateInline: "使用组件内联定义翻译",
    translateCli: "运行",
    translateGenerate: "生成翻译文件。",
    translateSwitch: "该应用程序支持动态语言切换，无需重新加载应用程序。",
    translateLearnMore: "了解更多",
  },
  TabLayout: {
    home: "主页",
    explore: "探索",
    yoyo: "哟哟",
    nope: "不",
  },
};
export default zh;