import formatAsJSON from "./formatAsJSON";
import formatAsJavaScript from "./formatAsJavaScript";
import formatAsTypeScript from "./formatAsTypeScript";
import { FileExtensions } from "../types";

const formatTranslatedContent = ({
  fileExtension,
  translatedContent,
  targetLanguage,
  isPrimary,
}: {
  fileExtension: FileExtensions;
  translatedContent: Record<string, any>;
  targetLanguage: string;
  isPrimary?: boolean;
}) => {
  // Decide how to phrase the warning message
  const commentForJSOrTS = isPrimary
    ? `// This file was generated by TranslateSheet.\n// Do NOT edit this file directly.\n// To change primary language strings, update your TranslateSheet object declarations.\n\n`
    : `// This file was generated by TranslateSheet.\n// Do NOT edit this file directly.\n// Make changes in the TranslateSheet dashboard.\n\n`;

  // For JSON, we can’t do comments, so we store the message in a key
  const messageForJSON = isPrimary
    ? "This file was generated by TranslateSheet. Do NOT edit this file directly. To change primary language strings, update your TranslateSheet object declarations."
    : "This file was generated by TranslateSheet. Do NOT edit this file directly. Make changes in the TranslateSheet dashboard.";

  // Conditionally format the content based on file extension
  if (fileExtension === ".json") {
    // Since JSON doesn't support comments, add a special key
    const jsonCopy = {
      _generatedByTranslateSheet: messageForJSON,
      ...translatedContent,
    };
    return formatAsJSON(jsonCopy);
  } else if (fileExtension === ".ts") {
    const tsContent = formatAsTypeScript(translatedContent, targetLanguage);
    return commentForJSOrTS + tsContent;
  } else if (fileExtension === ".js") {
    const jsContent = formatAsJavaScript(translatedContent, targetLanguage);
    return commentForJSOrTS + jsContent;
  } else {
    throw new Error(`Unsupported file extension: ${fileExtension}`);
  }
};

export default formatTranslatedContent;
