import fs from "fs";
import path from "path";

/**
 * Unflattens an object with dot-notation keys into a nested object.
 * For example, { "step1.title": "value" } becomes { step1: { title: "value" } }.
 *
 * @param obj - The object to unflatten.
 * @returns A nested object.
 */
function unflattenObject(obj: Record<string, any>): Record<string, any> {
  const result: Record<string, any> = {};
  for (const key in obj) {
    const value = obj[key];
    if (typeof value === "object" && value !== null && !Array.isArray(value)) {
      // Recursively unflatten any nested objects first.
      const nested = unflattenObject(value);
      // If the key itself contains a dot, process it.
      if (key.indexOf(".") !== -1) {
        const parts = key.split(".");
        let current = result;
        for (let i = 0; i < parts.length; i++) {
          const part = parts[i];
          if (i === parts.length - 1) {
            current[part] = nested;
          } else {
            if (!current[part] || typeof current[part] !== "object") {
              current[part] = {};
            }
            current = current[part];
          }
        }
      } else {
        // Merge with any existing value if necessary.
        if (result[key] && typeof result[key] === "object") {
          result[key] = { ...result[key], ...nested };
        } else {
          result[key] = nested;
        }
      }
    } else {
      // For non-object values, check for dot notation in the key.
      if (key.indexOf(".") !== -1) {
        const parts = key.split(".");
        let current = result;
        for (let i = 0; i < parts.length; i++) {
          const part = parts[i];
          if (i === parts.length - 1) {
            current[part] = value;
          } else {
            if (!current[part] || typeof current[part] !== "object") {
              current[part] = {};
            }
            current = current[part];
          }
        }
      } else {
        result[key] = value;
      }
    }
  }
  return result;
}

/**
 * Checks whether a string is a valid TypeScript identifier.
 *
 * @param key - The key to check.
 * @returns True if valid, false otherwise.
 */
function isValidIdentifier(key: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key);
}

/**
 * Recursively generates a nested type definition from an object.
 * Assumes all leaf values are strings.
 *
 * @param obj - The object to generate the type definition from.
 * @param indentLevel - The current indentation level.
 * @returns A string representing the type definition.
 */
function generateTypeDefinitionFromObject(obj: any, indentLevel = 1): string {
  const indent = "  ".repeat(indentLevel);
  const entries = Object.entries(obj);
  if (entries.length === 0) {
    return "{}";
  }
  const lines = entries.map(([key, value]) => {
    const formattedKey = isValidIdentifier(key) ? key : JSON.stringify(key);
    let typeStr: string;
    if (value !== null && typeof value === "object" && !Array.isArray(value)) {
      typeStr = generateTypeDefinitionFromObject(value, indentLevel + 1);
    } else {
      typeStr = "string";
    }
    return `${indent}${formattedKey}: ${typeStr};`;
  });
  return `{\n${lines.join("\n")}\n${"  ".repeat(indentLevel - 1)}}`;
}

/**
 * Generates a translations types file based on the provided primary language content.
 * The file will contain a single type definition named 'Translations'.
 *
 * @param primaryLanguageContent - The translations object (supports nested objects, even if keys are flattened).
 * @param output - The directory where the file should be saved.
 * @param filename - Optional filename; defaults to "translations.types.ts".
 * @returns The full path to the generated file.
 */
export function generateTranslationTypesFile(
  primaryLanguageContent: Record<string, any>,
  output: string,
  filename: string = "translations.types.ts"
): string {
  // Unflatten the object so that dot notation keys become nested.
  const nestedContent = unflattenObject(primaryLanguageContent);
  const typeDefinition = generateTypeDefinitionFromObject(nestedContent, 1);
  const fileContent = `// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

export type Translations = ${typeDefinition};
`;
  fs.mkdirSync(output, { recursive: true });
  const filePath = path.join(output, filename);
  fs.writeFileSync(filePath, fileContent, "utf-8");
  return filePath;
}
